### ISSUE TITLE
Homepage migration

### ISSUE THREAD

**Issue by RitaOak** [oaeproject/Cake#5]
When migrating the final version of Biscuit-ux for the homepage, keep in mind the following issues:

1. The search bar is now in prominence, which means that it will stay centered;
2. The search bar is on top of a background. This element can be changed by the corresponding tenant to a photo or a solid colour;
3. The modal must have a z-index higher than any other element in the homepage.

Consider adding the following tweaks in the future:

4. For `2`, include the possibility to drag the background and set it into the preferred position;
5. Search bar needs a filtering system

**Comment by brecke** [comment]
shall we close this?
