### ISSUE TITLE
Get open source icons for social media logos

### ISSUE THREAD

**Issue by brecke** [oaeproject/Cake#8]
On the authentication modal window there are icons for twitter, google and facebook buttons, but we need ones we can use without attribution. Not important just yet, but let's not forget to do this.

**Comment by brecke** [comment]
Let's recall how it looks like, today
![Screenshot 2021-03-26 at 15 55 37](https://user-images.githubusercontent.com/19879/112658896-c4c70200-8e4b-11eb-8589-1873bf60c2cd.png)

**Comment by RitaOak** [comment]
We can, ideally, get open source icons from [FontAwesome](https://fontawesome.com/). It's the default icon toolkit for Bulma.

**Comment by RitaOak** [comment]
A note that the set of icons for [polymer](https://www.webcomponents.org/element/@polymer/iron-icons) we had been using lacks the social media we need and that FontAwesome has a much more complete toolset.

**Comment by brecke** [comment]
be my guest, I just care about being pretty and having a proper license :) have fun!

**Comment by RitaOak** [comment]
Font awesome installed successfully

**Comment by RitaOak** [comment]
In progress

**Comment by RitaOak** [comment]
**WIP**

Styling and designing a more usable modal for sign in actions.
